namespace LojaDeRoupasAPI.Enums
{
    public enum Tipo
    {
        Calça,
        Camiseta,
        Camisa,
        Blusa,
        Legging,
        Intima,
        Casaco,
        Moletom,
        Short,
        Tactel,
        Luva,
        Touca,
        Bone,
        Meia,
        Chapeu,
        Jeans,
        Bolsa,
        Oculos,
        Pulseira,
        Colar,
        Cordao,
        Perfume,
        Creme, 
        Maquiagem,
        Botom, 
        Sombras,
        Hidratante,
        Rimel,
    }
}
